# Generated by Django 3.2.15 on 2022-10-18 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('allow_times', models.TextField(default='', validators=[django.core.validators.RegexValidator('^(?:[01]\\d|2[1-3]):[0-5]\\d(?::[0-5]\\d)?(?:,(?:[01]\\d|2[1-3]):[0-5]\\d(?::[0-5]\\d)?)*$', 'Please enter comma seperated times, without spaces, like so: 12:00,13:15')])),
                ('disabled_dates', models.TextField(default='', validators=[django.core.validators.RegexValidator('^(\\s{0,})(\\d{2}\\.\\d{2}\\.\\d{4})(,\\d{2}\\.\\d{2}\\.\\d{4}){1,}(\\s){0,}$', 'Please enter comma seperated dates (dd.mm.yyyy), without spaces, like so: 01.11.2028,02.11.2028')])),
                ('disabled_weekdays', models.TextField(default='', validators=[django.core.validators.RegexValidator('^[0-6](,[0-6])*$', "Please enter valid numbers for weekdays, seperated by comma's. Values from 0-6, starting with sunday at value 0 (0,1,3 for example).")])),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='short_description',
            field=models.CharField(default='short description', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='duration',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('treatment_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salon.treatment')),
            ],
        ),
    ]
