# Generated by Django 3.2.15 on 2022-09-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_treatment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='short_description',
            field=models.CharField(default='okay', max_length=39),
            preserve_default=False,
        ),
    ]
