# Generated by Django 3.2.15 on 2022-10-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20221012_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='type',
            new_name='treatment_name',
        ),
    ]
