# Generated by Django 3.2.15 on 2022-10-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_rename_type_appointment_treatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salon.treatment'),
        ),
    ]
