# Generated by Django 3.2.15 on 2022-10-05 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_treatment_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_times', models.TextField(default='', validators=[django.core.validators.RegexValidator('^(?:[01]\\d|2[1-3]):[0-5]\\d(?::[0-5]\\d)?(?:,(?:[01]\\d|2[1-3]):[0-5]\\d(?::[0-5]\\d)?)*$', 'Please enter comma seperated times, like so: 12:00, 13:15')])),
            ],
        ),
    ]
