# Generated by Django 3.2.15 on 2022-10-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_treatment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_name', to='salon.treatment'),
        ),
    ]
