# Generated by Django 3.2.15 on 2022-10-06 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_planning_disabled_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='title',
            field=models.CharField(default='Main planning', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planning',
            name='disabled_days',
            field=models.TextField(default='', validators=[django.core.validators.RegexValidator('^(\\s{0,})(\\d{2}\\.\\d{2}\\.\\d{4})(,\\d{2}\\.\\d{2}\\.\\d{4}){1,}(\\s){0,}$', 'Please enter comma seperated dates (dd.mm.yyyy), without spaces, like so: 01.11.2028,02.11.2028')]),
        ),
    ]
