# Generated by Django 3.2.15 on 2022-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(default='image', max_length=150),
        ),
    ]
