# Generated by Django 3.2.15 on 2022-10-07 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20221007_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='disabled_weekdays',
            field=models.TextField(default='', validators=[django.core.validators.RegexValidator('^[0-6](,[0-6])*$', "Please enter valid numbers for weekdays, seperated by comma's. Values from 0-6, starting with sunday at value 0 (0,1,3 for example).")]),
        ),
    ]
