# Generated by Django 3.2.15 on 2022-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_alter_planning_disabled_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
