# Generated by Django 3.2.15 on 2022-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_planning_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
