# Generated by Django 3.2.15 on 2022-10-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salon.appointment'),
        ),
    ]
